name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files }}

  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
        python-version: [ '3.8', '3.9', '3.10' ]
        include:
          - os: windows-latest
            python: 38
            python-version: '3.8'
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest
            python: 39
            python-version: '3.9'
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest
            python: 310
            python-version: '3.10'
            bitness: 64
            platform_id: win_amd64

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install
        run: python -m pip install .[dev,deep_learning]

      - name: Tests
        run: python -m pytest


  codecov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Disable Numba JIT
        run: echo "NUMBA_DISABLE_JIT=1" >> $GITHUB_ENV

      - name: Install
        run: python -m pip install .[dev,deep_learning]

      - name: Tests
        run: python -m pytest --cov=tsml_eval --cov-report=xml

      - uses: codecov/codecov-action@v3
